set_pixel:
  description: 'Sets pixel value.'
  fields:
    topic:
      description: 'Define the topic to use.'
      example: '/led/led/set'
    red:
      description: 'Sets value for the color red.'
      example: 0
    green:
      description: 'Sets value for the color red.'
      example: 255
    blue:
      description: 'Sets value for the color red.'
      example: 0
    white:
      description: 'Sets white value.'
      example: 0
    from:
      description: 'Define start pixel.'
      example: 10
    to:
      description: 'Define start pixel.'
      example: 100
